stages:
  # Compilation, tests, testing database creation scripts
  - "compilation, unit tests, database creation tests"
  - "integration and functional tests"
  - "compatibility tests"
  - "deploy"
jobs:
  include:
    - stage: "compilation, unit tests, database creation tests"
      name: "Compilation and unit tests"
      dist: trusty # https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images - Trusty supports java 8
      language: java
      jdk: oraclejdk8
      install: skip
      cache:
        directories:
          - $HOME/.m2
      script: mvn clean install

    - stage: "compilation, unit tests, database creation tests"
      name: "Database creation tests for multiple postgres versions 9.6, 10, 11, 12, 13"
      language: bash
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
      services:
        - docker
      script: export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && bats/run_bats_test_for_all_db_version.sh

    - stage: "compilation, unit tests, database creation tests"
      name: "Testing configuration jar"
      dist: trusty # https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images - Trusty supports java 8
      language: java
      jdk: oraclejdk8
      install: skip
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
        - sudo apt-get -y install libxml2-utils
      addons:
        apt:
          update: true
      cache:
        directories:
          - $HOME/.m2
      script: mvn -DskipTests --quiet clean install && export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && bats -tr bats/configuration-jar

    - stage: "integration and functional tests"
      name: "Integration and functional tests in postgresql-core module"
      dist: trusty # https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images - Trusty supports java 8
      language: java
      jdk: oraclejdk8
      install: skip
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      before_script:
        - psql -f 'db_scripts/prepare_postgresql-core_db.sql' -U postgres
      cache:
        directories:
          - $HOME/.m2
      script: mvn -DskipTests --quiet clean install && mvn -pl :postgresql-core -P !unit-tests,integration-tests test && mvn -pl :postgresql-core-functional-tests -P !unit-tests,functional-tests test

    - stage: "integration and functional tests"
      name: "E2E smoke tests for configuration jar"
      dist: trusty # https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images - Trusty supports java 8
      language: java
      jdk: oraclejdk8
      install: skip
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      before_script:
        - psql -f 'db_scripts/prepare_postgresql-core_db.sql' -U postgres
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
      cache:
        directories:
          - $HOME/.m2
      script: mvn -DskipTests --quiet clean install && export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && bats -tr bats/configuration-integration

    - stage: "integration and functional tests"
      name: "Testing configuration jar"
      dist: trusty # https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images - Trusty supports java 8
      language: java
      jdk: oraclejdk8
      install: skip
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
        - sudo apt-get -y install libxml2-utils
      addons:
        apt:
          update: true
      cache:
        directories:
          - $HOME/.m2
      script: mvn -DskipTests --quiet clean install && export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && bats -tr bats/configuration-jar

    - stage: "compatibility tests"
      name: "Running integration and functional tests that checks if code is compatible with postgres versions 10, 11, 12, 13"
      dist: trusty # https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images - Trusty supports java 8
      language: java
      jdk: oraclejdk8
      install: skip
      services:
        - docker
      cache:
        directories:
          - $HOME/.m2
      script: bats/run_integration_test_for_all_db_version.sh

    - stage: "deploy"
      name: "Deploy project"
      if: |
        tag IS present
      dist: trusty # https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images - Trusty supports java 8
      language: java
      jdk: oraclejdk8
      install: skip
      cache:
        directories:
          - $HOME/.m2
      script: mvn -DskipTests clean install
      deploy:
        provider: script
        script: bash deploy/release.sh
        on:
          tags: true
          branch: release